### ISSUE TITLE
Unnecessary test dependency?

### ISSUE THREAD

**Issue by wasamasa** [amagura/eggs#7]
Now that `setup-helper` finally deprecated the `include` usage, a number of eggs broke, including `kvlists` which is a test dependency for the readline egg.  As the test file does only use `kvlist?`, I wonder whether it's necessary to use this dependency at all.  One could easily copy this one definition and just use it.

What could also work is thinking a bit more about the tested variable, `readline#session`.  It is defined as a list with four special keys.  Why not test for the presence of each with `kvlist-ref` or a copied definition instead?

**Comment by amagura** [comment]
So I copied the definition of `kvlist?` into the `run.scm` file and added the author's information to the `AUTHORS`.  

![](http://66.media.tumblr.com/d58c46e4b88a8b870b276becf5af107e/tumblr_npfyuhZeHY1tuimtao8_500.gif)
